# base image
FROM node:10

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install

# copy entire app to workdir
COPY . /app

# specify the port number the container should expose
EXPOSE 4200

# run the application
CMD node_modules/@angular/cli/bin/ng serve --host 0.0.0.0 --disable-host-check
