AWSTemplateFormatVersion: '2010-09-09'
Description: The Cognito stack includes UserPool and UserClient resources
Parameters:
  APIName:
    Type: String
    Description: The name of AppSync API, be used to generate resources name (prefix ${APIName})
    MinLength: 5
    MaxLength: 16
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9_]*$'
  TriggerFunc:
    Type: String
    Description: The name of Lambda function is triggered by Cognito
Resources:
  AddUserTriggerResourcePolicy:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TriggerFunc
      Principal: cognito-idp.amazonaws.com
      SourceArn: !Sub
        - arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}
        - { UserPoolId: !Ref UserPool }
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${APIName}-userpool
      Schema:
        - Name: family_name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: given_name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: phone_number
          AttributeDataType: String
          Mutable: false
          Required: true
      LambdaConfig:
        PreSignUp: !Ref TriggerFunc
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${APIName}-userpool-client
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      GenerateSecret: false
      UserPoolId: !Ref UserPool
Outputs:
  CognitoUserPoolId:
    Description: The Pool ID of the Cognito User Pool
    Value: !Ref UserPool
  CognitoUserPoolClientId:
    Description: The Client ID for AWS AppSync Auth
    Value: !Ref UserPoolClient